### ISSUE TITLE
Kanban Board Project Setup

### ISSUE THREAD

**Issue by trace-kadenyi** [TracK92/JavaScript-Capstone-Group-Project#21]
- There are 2 members in my group.
      - Student A: TracK92
      - Student B: chimwemwe007
- Below is the link to our GitHub Project: 
         - https://github.com/TracK92/JavaScript-Capstone-Group-Project/projects/1

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] All cards should be assigned to team members. You should see a circle with the user's avatar on each card. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by trace-kadenyi** [comment]
Dear Reviewer, 
Thank you for your comment. I have assigned the cards accordingly. Kindly re-review my work.

**Comment by keroloussamy** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏
